baseURL = "https://aiuncharted.dev/"
languageCode = "en-us"
title = "AI Uncharted"
theme = "LoveIt"

# Basic Hugo settings
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
disableKinds = ["taxonomy", "term"]

# Ignore build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Menu config
[menu]
  [[menu.main]]
    weight = 10
    identifier = "about"
    name = "About Me"
    url = "/about/"
  [[menu.main]]
    weight = 20
    identifier = "why"
    name = "Why AI Uncharted?"
    url = "/why/"
  [[menu.main]]
    weight = 30
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

# Site parameters
[params]
  defaultTheme = "auto"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "AI Uncharted"
  description = "A personal lab for exploring, testing, and gradually mastering artificial intelligence through hands-on experimentation rather than theory."
  
  # Author config
  [params.author]
    name = "Erik Nergaard"
    email = ""
    link = ""

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "AI Uncharted"
      post = " - This isn't a showcase. It's a workshop."
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2024
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Search config - disabled
  [params.search]
    enable = false

  # Home page config
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      title = ""
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      typeit = true
      social = false
    [params.home.posts]
      enable = true
      paginate = 6

  # Page config
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.comment]
      enable = false
    [params.page.share]
      enable = false

  # CDN config
  [params.cdn]
    data = "jsdelivr.yml"

  # Compatibility config
  [params.compatibility]
    polyfill = false
    objectFit = false

# Markup configuration
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Output formats
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
