baseURL = "https://aiuncharted.dev/"
languageCode = "en-us"
title = "AI Uncharted"
theme = "LoveIt"

[params]
  # LoveIt theme specific parameters
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  # more params can be added here as needed

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "why"
    name = "Why AI Uncharted?"
    url = "/why/"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup.highlight]
  anchorLineNos = true
  codeFences = true
  guessSyntax = true
  lineNos = true
  noClasses = false
  style = "dracula" # Or any other style you prefer
