baseURL = "https://aiuncharted.dev/"
languageCode = "en-us"
title = "AI Uncharted - This isn’t a showcase. It’s a workshop"
theme = "ananke"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "why"
    name = "Why AI Uncharted?"
    url = "/why/"
    weight = 20
