baseURL = "https://aiuncharted.dev/"
languageCode = "en-us"
title = "AI Uncharted"
theme = "PaperMod"

# Basic Hugo settings
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
buildFuture = true

# Pagination configuration (Hugo v0.128.0+ syntax)
[pagination]
  pagerSize = 10
  path = "page"

# Content sorting
[frontmatter]
  date = ["date", "publishDate", "lastmod"]

# Navigation Menu
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Why AI Uncharted"
    url = "/why-ai-uncharted/"
    weight = 2

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4

# Site parameters
[params]
  author = "Erik Nergaard"
  description = "A personal lab for exploring, testing, and gradually mastering artificial intelligence through hands-on experimentation rather than theory."
  
  # PaperMod specific features
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  
  # Social and metadata
  images = [""]
  
  # Post sorting - newest first
  mainSections = ["posts"]
  
  [params.assets]
    disable_mermaid = false

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
