baseURL = "https://aiuncharted.dev/"
languageCode = "en-us"
title = "AI Uncharted"
theme = "ananke"

# Basic Hugo settings
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

# Menu config
[menu]
  [[menu.main]]
    weight = 10
    identifier = "about"
    name = "About Me"
    url = "/about/"
  [[menu.main]]
    weight = 20
    identifier = "why"
    name = "Why AI Uncharted?"
    url = "/why/"
  [[menu.main]]
    weight = 30
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

# Site parameters
[params]
  author = "Erik Nergaard"
  description = "A personal lab for exploring, testing, and gradually mastering artificial intelligence through hands-on experimentation rather than theory."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 3

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
